artifact_location: file:///c:/Users/xdxd2/Sunny_VS_worksapce/Sunny_python/ML/MLOps_fundamentals/MLflow/basic/mytracks/686184249410295148
creation_time: 1706495340847
experiment_id: '686184249410295148'
last_update_time: 1706495340847
lifecycle_stage: active
name: experment_for_url
