artifact_uri: file:///c:/Users/xdxd2/Sunny_VS_worksapce/Sunny_python/ML/MLOps_fundamentals/MLflow/basic/myartifacts/77acae23f0a34adab976b4b80d039426/artifacts
end_time: 1706495471691
entry_point_name: ''
experiment_id: '695845020369581940'
lifecycle_stage: active
run_id: 77acae23f0a34adab976b4b80d039426
run_name: nervous-donkey-437
run_uuid: 77acae23f0a34adab976b4b80d039426
source_name: ''
source_type: 4
source_version: ''
start_time: 1706495466228
status: 3
tags: []
user_id: xdxd2
