channels:
- conda-forge
dependencies:
- python=3.10.7
- pip<=23.3.2
- pip:
  - mlflow==2.10.0
  - cloudpickle==2.2.0
  - lz4==4.3.2
  - numpy==1.26.3
  - packaging==23.1
  - psutil==5.9.2
  - pyyaml==6.0
  - scikit-learn==1.1.2
  - scipy==1.11.2
name: mlflow-env
