artifact_location: file:///c:/Users/xdxd2/Sunny_VS_worksapce/Sunny_python/ML/MLOps_fundamentals/MLflow/basic/mytracks/0
creation_time: 1706495340818
experiment_id: '0'
last_update_time: 1706495340818
lifecycle_stage: active
name: Default
