artifact_location: file:///c:/Users/xdxd2/Sunny_VS_worksapce/Sunny_python/ML/MLOps_fundamentals/MLflow/basic/myartifacts
creation_time: 1706495465773
experiment_id: '695845020369581940'
last_update_time: 1706495465773
lifecycle_stage: active
name: exp_create_exp_artifact
